#!/usr/bin/env bash

LOG_FILE="./output.log"
DURATION=8
EXTERNAL_DIR="./external"
ROM_DIR="$EXTERNAL_DIR/gb-test-roms"
DOCTOR_DIR="$EXTERNAL_DIR/gameboy-doctor"
ROM_BASE_DIR="$ROM_DIR/cpu_instrs/individual"
DOCTOR_PATH="$DOCTOR_DIR/gameboy-doctor"

roms=("" "01-special.gb" "02-interrupts.gb" "03-op sp,hl.gb" "04-op r,imm.gb" "05-op rp.gb" "06-ld r,r.gb" "07-jr,jp,call,ret,rst.gb" "08-misc instrs.gb" "09-op r,r.gb" "10-bit ops.gb" "11-op a,(hl).gb")

check_dependencies() {
    mkdir -p "$EXTERNAL_DIR"
    if [ ! -d "$DOCTOR_DIR" ]; then
        git clone https://github.com/robert/gameboy-doctor.git "$DOCTOR_DIR"
    fi
    if [ ! -d "$ROM_DIR" ]; then
        git clone https://github.com/retrio/gb-test-roms.git "$ROM_DIR"
    fi
}

build_emulator() {
    if cargo build --release --quiet 2> /dev/null; then
        echo -e "${GREEN}✅ Build successful!${NC}"
    else
        echo -e "${RED}❌ Build failed. Check your Rust code.${NC}"
        exit 1
    fi
}

run_single_test() {
    local index=$1
    local rom_name="${roms[$index]}"
    local rom_path="${ROM_BASE_DIR}/${rom_name}"    
    
    if [[ ! -f "$rom_path" ]]; then
        echo -e "${RED}⚠️  ROM not found: $rom_path${NC}"
        return
    fi

    rm -f "${LOG_FILE}"
    
    export RUST_BACKTRACE=1
    # This lines implementation requires, doctor to have unzipped the files once.
    lines=$(wc -l < ${DOCTOR_DIR}/truth/unzipped/cpu_instrs/${index}.log)
    timeout --foreground "${DURATION}" ./target/release/gameboy_rs --load-rom "${rom_path}" --log-path "${LOG_FILE}" --debug-doctor "${lines}"

    if [ ! -s "$LOG_FILE" ]; then
        echo -e "${RED}❌ Error: No log data generated.${NC}"
        return
    fi

    echo -e "${GREEN}🩺 Running Doctor Check...${NC}"
    python3 "$DOCTOR_PATH" "$LOG_FILE" cpu_instrs "$index"
}

# --- Execution Flow ---

check_dependencies

build_emulator

echo -e "\n${YELLOW}Choose a test (1-11) or press [ENTER] for ALL:${NC}"
read -p "👉 " user_input


if [[ -z "$user_input" ]]; then
    for i in {1..11}; do
        run_single_test "$i"
    done
else
    selection=$((10#$user_input))
    run_single_test "$selection"
fi

